### ISSUE TITLE
readMeasurement

### ISSUE THREAD

**Issue by nikkadim** [adafruit/Adafruit_MLX90395#1]
0x80  - is for RESET command not for reading measurements.
```
bool Adafruit_MLX90395::readMeasurement(float *x, float *y, float *z) {
  uint8_t tx[1] = {0x80}; // Read memory command
  uint8_t rx[12] = {0};   // status, crc, X16, Y16, Z16, T16, V16
```

**Comment by siddacious** [comment]
0x80 is used in I2C mode for reading, as shown in this diagram from page 81 of the datasheet:
![image](https://user-images.githubusercontent.com/1183985/99849139-dd3aaf00-2b2f-11eb-8ec0-edfd8692d68a.png)
